model_definitions = [
    {
        "Model": "DeepSeek-R1",
        "Parameters": "7B",
        "Size": "4.7GB",
        "Download": "ollama run deepseek-r1",
    },
    {
        "Model": "DeepSeek-R1",
        "Parameters": "671B",
        "Size": "404GB",
        "Download": "ollama run deepseek-r1:671b",
    },
    {
        "Model": "Llama 3.3",
        "Parameters": "70B",
        "Size": "43GB",
        "Download": "ollama run llama3.3",
    },
    {
        "Model": "Llama 3.2",
        "Parameters": "3B",
        "Size": "2.0GB",
        "Download": "ollama run llama3.2",
    },
    {
        "Model": "Llama 3.2",
        "Parameters": "1B",
        "Size": "1.3GB",
        "Download": "ollama run llama3.2:1b",
    },
    {
        "Model": "Llama 3.2 Vision",
        "Parameters": "11B",
        "Size": "7.9GB",
        "Download": "ollama run llama3.2-vision",
    },
    {
        "Model": "Llama 3.2 Vision",
        "Parameters": "90B",
        "Size": "55GB",
        "Download": "ollama run llama3.2-vision:90b",
    },
    {
        "Model": "Llama 3.1",
        "Parameters": "8B",
        "Size": "4.7GB",
        "Download": "ollama run llama3.1",
    },
    {
        "Model": "Llama 3.1",
        "Parameters": "405B",
        "Size": "231GB",
        "Download": "ollama run llama3.1:405b",
    },
    {
        "Model": "Phi 4",
        "Parameters": "14B",
        "Size": "9.1GB",
        "Download": "ollama run phi4",
    },
    {
        "Model": "Phi 3 Mini",
        "Parameters": "3.8B",
        "Size": "2.3GB",
        "Download": "ollama run phi3",
    },
    {
        "Model": "Gemma 2",
        "Parameters": "2B",
        "Size": "1.6GB",
        "Download": "ollama run gemma2:2b",
    },
    {
        "Model": "Gemma 2",
        "Parameters": "9B",
        "Size": "5.5GB",
        "Download": "ollama run gemma2",
    },
    {
        "Model": "Gemma 2",
        "Parameters": "27B",
        "Size": "16GB",
        "Download": "ollama run gemma2:27b",
    },
    {
        "Model": "Mistral",
        "Parameters": "7B",
        "Size": "4.1GB",
        "Download": "ollama run mistral",
    },
    {
        "Model": "Moondream 2",
        "Parameters": "1.4B",
        "Size": "829MB",
        "Download": "ollama run moondream",
    },
    {
        "Model": "Neural Chat",
        "Parameters": "7B",
        "Size": "4.1GB",
        "Download": "ollama run neural-chat",
    },
    {
        "Model": "Starling",
        "Parameters": "7B",
        "Size": "4.1GB",
        "Download": "ollama run starling-lm",
    },
    {
        "Model": "Code Llama",
        "Parameters": "7B",
        "Size": "3.8GB",
        "Download": "ollama run codellama",
    },
    {
        "Model": "Llama 2 Uncensored",
        "Parameters": "7B",
        "Size": "3.8GB",
        "Download": "ollama run llama2-uncensored",
    },
    {
        "Model": "LLaVA",
        "Parameters": "7B",
        "Size": "4.5GB",
        "Download": "ollama run llava",
    },
    {
        "Model": "Solar",
        "Parameters": "10.7B",
        "Size": "6.1GB",
        "Download": "ollama run solar",
    },
]
